[package]
name = "terracotta"
version = "0.1.0-alpha"
edition = "2024"

[dependencies]
chrono = "0.4.42"
fastnbt = "2.6.0"
fern = "0.7.1"
log = "0.4.28"
rand = "0.9.2"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.8"
